// samples/browser-esm-vite-vue3-typescript/src/components/Editor.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, toRaw } from 'vue';
import * as monaco from 'monaco-editor/esm/vs/editor/editor.api';

const editorRef = ref<HTMLElement | null>(null);
const editorInstance = ref<monaco.editor.IStandaloneCodeEditor | null>(null);

onMounted(() => {
	if (editorRef.value && !editorInstance.value) {
		editorInstance.value = monaco.editor.create(editorRef.value, {
			value: ['function x() {', '\tconsole.log("Hello world!");', '}'].join('\n'),
			language: 'typescript'
		});
	}
});

onUnmounted(() => toRaw(editorInstance.value)?.dispose());
</script>

<template>
	<div class="editor" ref="editorRef" />
</template>

<style scoped>
.editor {
	width: 100vw;
	height: 100vh;
}
</style>

// samples/browser-esm-vite-react/src/components/Editor.tsx
import * as monaco from 'monaco-editor/esm/vs/editor/editor.api'
import { useEffect, useRef } from 'react'

import styles from './Editor.module.css'

export function Editor() {
  const editorRef = useRef<monaco.editor.IStandaloneCodeEditor | null>(null)
  const containerRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (!containerRef.current) return

    editorRef.current = monaco.editor.create(
      containerRef.current,
      {
        value: ['function x() {', '\tconsole.log("Hello world!");', '}'].join('\n'),
        language: 'typescript',
      },
    )

    return editorRef.current.dispose.bind(editorRef.current)
  }, [])

  return <div ref={containerRef} className={styles.Editor} />
}
