// samples/browser-esm-vite-react/src/components/Editor.tsx
import * as monaco from 'monaco-editor/esm/vs/editor/editor.api'
import { useEffect, useRef } from 'react'

import styles from './Editor.module.css'

export function Editor() {
  const editorRef = useRef<monaco.editor.IStandaloneCodeEditor | null>(null)
  const containerRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (!containerRef.current) return

    editorRef.current = monaco.editor.create(
      containerRef.current,
      {
        value: ['function x() {', '\tconsole.log("Hello world!");', '}'].join('\n'),
        language: 'typescript',
      },
    )

    return editorRef.current.dispose.bind(editorRef.current)
  }, [])

  return <div ref={containerRef} className={styles.Editor} />
}

// samples/browser-esm-vite-vue/src/components/Editor.vue
<template>
	<div class="editor" ref="editorContainer"></div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import * as monaco from 'monaco-editor/esm/vs/editor/editor.api';

const editorContainer = ref<HTMLDivElement | null>(null);
let editor: monaco.editor.IStandaloneCodeEditor | null = null;

onMounted(() => {
	if (editorContainer.value) {
		editor = monaco.editor.create(editorContainer.value, {
			value: ['function x() {', '\tconsole.log("Hello world!");', '}'].join('\n'),
			language: 'typescript'
		});
	}
});

onUnmounted(() => {
	editor?.dispose();
});
</script>

<style scoped>
.editor {
	width: 100vw;
	height: 100vh;
}
</style>
